//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConDep.Dsl.LoadBalancer.Ace.Ace41 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://anm.cisco.com")]
    public partial class WSException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://anm.cisco.com")]
    public partial class SessionToken : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sid {
            get {
                return this.sidField;
            }
            set {
                this.sidField = value;
                this.RaisePropertyChanged("sid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://anm.cisco.com", ConfigurationName="Ace41.OperationManager")]
    public interface OperationManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConDep.Dsl.LoadBalancer.Ace.Ace41.WSException), Action="", Name="WSException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SessionToken")]
        ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken login(string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConDep.Dsl.LoadBalancer.Ace.Ace41.WSException), Action="", Name="WSException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        void logout(ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken);
        
        // CODEGEN: Parameter 'serverfarms' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConDep.Dsl.LoadBalancer.Ace.Ace41.WSException), Action="", Name="WSException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="serverfarms")]
        ConDep.Dsl.LoadBalancer.Ace.Ace41.listServerFarmsResponse listServerFarms(ConDep.Dsl.LoadBalancer.Ace.Ace41.listServerFarmsRequest request);
        
        // CODEGEN: Parameter 'Rservers' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConDep.Dsl.LoadBalancer.Ace.Ace41.WSException), Action="", Name="WSException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Rservers")]
        ConDep.Dsl.LoadBalancer.Ace.Ace41.listRserversResponse listRservers(ConDep.Dsl.LoadBalancer.Ace.Ace41.listRserversRequest request);
        
        // CODEGEN: Parameter 'SfRservers' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConDep.Dsl.LoadBalancer.Ace.Ace41.WSException), Action="", Name="WSException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SfRservers")]
        ConDep.Dsl.LoadBalancer.Ace.Ace41.listServerfarmRserversResponse listServerfarmRservers(ConDep.Dsl.LoadBalancer.Ace.Ace41.listServerfarmRserversRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConDep.Dsl.LoadBalancer.Ace.Ace41.WSException), Action="", Name="WSException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        void addRserverToServerfarm(ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken, ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID deviceID, string serverfarmname, ConDep.Dsl.LoadBalancer.Ace.Ace41.Rserver rserver, int port);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConDep.Dsl.LoadBalancer.Ace.Ace41.WSException), Action="", Name="WSException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        void removeRserverFromServerfarm(ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken, ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID deviceID, ConDep.Dsl.LoadBalancer.Ace.Ace41.SfRserver rserver);
        
        // CODEGEN: Parameter 'DeviceIDs' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConDep.Dsl.LoadBalancer.Ace.Ace41.WSException), Action="", Name="WSException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DeviceIDs")]
        ConDep.Dsl.LoadBalancer.Ace.Ace41.listDeviceIdsResponse listDeviceIds(ConDep.Dsl.LoadBalancer.Ace.Ace41.listDeviceIdsRequest request);
        
        // CODEGEN: Parameter 'DeviceIDs' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConDep.Dsl.LoadBalancer.Ace.Ace41.WSException), Action="", Name="WSException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DeviceIDs")]
        ConDep.Dsl.LoadBalancer.Ace.Ace41.listVirtualContextsResponse listVirtualContexts(ConDep.Dsl.LoadBalancer.Ace.Ace41.listVirtualContextsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConDep.Dsl.LoadBalancer.Ace.Ace41.WSException), Action="", Name="WSException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        void activateServerfarmRserver(ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken, ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID deviceID, ConDep.Dsl.LoadBalancer.Ace.Ace41.SfRserver rserver, string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConDep.Dsl.LoadBalancer.Ace.Ace41.WSException), Action="", Name="WSException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        void suspendServerfarmRserver(ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken, ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID deviceID, ConDep.Dsl.LoadBalancer.Ace.Ace41.SfRserver rserver, ConDep.Dsl.LoadBalancer.Ace.Ace41.SuspendState suspendState, string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConDep.Dsl.LoadBalancer.Ace.Ace41.WSException), Action="", Name="WSException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        void changeServerfarmRserverWeight(ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken, ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID deviceID, ConDep.Dsl.LoadBalancer.Ace.Ace41.SfRserver rserver, string reason);
        
        // CODEGEN: Parameter 'VMMappingInfos' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConDep.Dsl.LoadBalancer.Ace.Ace41.WSException), Action="", Name="WSException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="VMMappingInfos")]
        ConDep.Dsl.LoadBalancer.Ace.Ace41.getVMMappingInfoResponse getVMMappingInfo(ConDep.Dsl.LoadBalancer.Ace.Ace41.getVMMappingInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool isEmptyOrNull(string arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConDep.Dsl.LoadBalancer.Ace.Ace41.WSException), Action="", Name="WSException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        void validateIPAddress(string arg0);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://anm.cisco.com")]
    public partial class DeviceID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private DeviceType deviceTypeField;
        
        private bool deviceTypeFieldSpecified;
        
        private string ipAddrField;
        
        private string slotField;
        
        private string chassisIPAddrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DeviceType deviceType {
            get {
                return this.deviceTypeField;
            }
            set {
                this.deviceTypeField = value;
                this.RaisePropertyChanged("deviceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deviceTypeSpecified {
            get {
                return this.deviceTypeFieldSpecified;
            }
            set {
                this.deviceTypeFieldSpecified = value;
                this.RaisePropertyChanged("deviceTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ipAddr {
            get {
                return this.ipAddrField;
            }
            set {
                this.ipAddrField = value;
                this.RaisePropertyChanged("ipAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string slot {
            get {
                return this.slotField;
            }
            set {
                this.slotField = value;
                this.RaisePropertyChanged("slot");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string chassisIPAddr {
            get {
                return this.chassisIPAddrField;
            }
            set {
                this.chassisIPAddrField = value;
                this.RaisePropertyChanged("chassisIPAddr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://anm.cisco.com")]
    public enum DeviceType {
        
        /// <remarks/>
        CAT6K,
        
        /// <remarks/>
        ACE_BLADE,
        
        /// <remarks/>
        VIRTUAL_CONTEXT,
        
        /// <remarks/>
        ACE4710,
        
        /// <remarks/>
        GSS,
        
        /// <remarks/>
        CSS,
        
        /// <remarks/>
        CSM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://anm.cisco.com")]
    public partial class Serverfarm : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private serverFarmType serverFarmTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public serverFarmType serverFarmType {
            get {
                return this.serverFarmTypeField;
            }
            set {
                this.serverFarmTypeField = value;
                this.RaisePropertyChanged("serverFarmType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://anm.cisco.com")]
    public enum serverFarmType {
        
        /// <remarks/>
        host,
        
        /// <remarks/>
        redirect,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listServerFarms", WrapperNamespace="http://anm.cisco.com", IsWrapped=true)]
    public partial class listServerFarmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID deviceID;
        
        public listServerFarmsRequest() {
        }
        
        public listServerFarmsRequest(ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken, ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID deviceID) {
            this.sessionToken = sessionToken;
            this.deviceID = deviceID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listServerFarmsResponse", WrapperNamespace="http://anm.cisco.com", IsWrapped=true)]
    public partial class listServerFarmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConDep.Dsl.LoadBalancer.Ace.Ace41.Serverfarm[] serverfarms;
        
        public listServerFarmsResponse() {
        }
        
        public listServerFarmsResponse(ConDep.Dsl.LoadBalancer.Ace.Ace41.Serverfarm[] serverfarms) {
            this.serverfarms = serverfarms;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://anm.cisco.com")]
    public partial class Rserver : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private type typeField;
        
        private string ipAddrField;
        
        private state stateField;
        
        private int weightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public type type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ipAddr {
            get {
                return this.ipAddrField;
            }
            set {
                this.ipAddrField = value;
                this.RaisePropertyChanged("ipAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public state state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("weight");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://anm.cisco.com")]
    public enum type {
        
        /// <remarks/>
        host,
        
        /// <remarks/>
        redirect,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://anm.cisco.com")]
    public enum state {
        
        /// <remarks/>
        IS,
        
        /// <remarks/>
        OOS,
        
        /// <remarks/>
        ISS,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listRservers", WrapperNamespace="http://anm.cisco.com", IsWrapped=true)]
    public partial class listRserversRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID deviceID;
        
        public listRserversRequest() {
        }
        
        public listRserversRequest(ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken, ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID deviceID) {
            this.sessionToken = sessionToken;
            this.deviceID = deviceID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listRserversResponse", WrapperNamespace="http://anm.cisco.com", IsWrapped=true)]
    public partial class listRserversResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConDep.Dsl.LoadBalancer.Ace.Ace41.Rserver[] Rservers;
        
        public listRserversResponse() {
        }
        
        public listRserversResponse(ConDep.Dsl.LoadBalancer.Ace.Ace41.Rserver[] Rservers) {
            this.Rservers = Rservers;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://anm.cisco.com")]
    public partial class SfRserver : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string serverfarmNameField;
        
        private string realserverNameField;
        
        private realServerStates adminStateField;
        
        private int weightField;
        
        private bool weightFieldSpecified;
        
        private int portField;
        
        private string ipAddrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string serverfarmName {
            get {
                return this.serverfarmNameField;
            }
            set {
                this.serverfarmNameField = value;
                this.RaisePropertyChanged("serverfarmName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string realserverName {
            get {
                return this.realserverNameField;
            }
            set {
                this.realserverNameField = value;
                this.RaisePropertyChanged("realserverName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public realServerStates adminState {
            get {
                return this.adminStateField;
            }
            set {
                this.adminStateField = value;
                this.RaisePropertyChanged("adminState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("weight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool weightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
                this.RaisePropertyChanged("weightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
                this.RaisePropertyChanged("port");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ipAddr {
            get {
                return this.ipAddrField;
            }
            set {
                this.ipAddrField = value;
                this.RaisePropertyChanged("ipAddr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://anm.cisco.com")]
    public enum realServerStates {
        
        /// <remarks/>
        IS,
        
        /// <remarks/>
        OOS,
        
        /// <remarks/>
        ISS,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listServerfarmRservers", WrapperNamespace="http://anm.cisco.com", IsWrapped=true)]
    public partial class listServerfarmRserversRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID deviceID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string serverfarmname;
        
        public listServerfarmRserversRequest() {
        }
        
        public listServerfarmRserversRequest(ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken, ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID deviceID, string serverfarmname) {
            this.sessionToken = sessionToken;
            this.deviceID = deviceID;
            this.serverfarmname = serverfarmname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listServerfarmRserversResponse", WrapperNamespace="http://anm.cisco.com", IsWrapped=true)]
    public partial class listServerfarmRserversResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConDep.Dsl.LoadBalancer.Ace.Ace41.SfRserver[] SfRservers;
        
        public listServerfarmRserversResponse() {
        }
        
        public listServerfarmRserversResponse(ConDep.Dsl.LoadBalancer.Ace.Ace41.SfRserver[] SfRservers) {
            this.SfRservers = SfRservers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listDeviceIds", WrapperNamespace="http://anm.cisco.com", IsWrapped=true)]
    public partial class listDeviceIdsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceType deviceType;
        
        public listDeviceIdsRequest() {
        }
        
        public listDeviceIdsRequest(ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken, ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceType deviceType) {
            this.sessionToken = sessionToken;
            this.deviceType = deviceType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listDeviceIdsResponse", WrapperNamespace="http://anm.cisco.com", IsWrapped=true)]
    public partial class listDeviceIdsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID[] DeviceIDs;
        
        public listDeviceIdsResponse() {
        }
        
        public listDeviceIdsResponse(ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID[] DeviceIDs) {
            this.DeviceIDs = DeviceIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listVirtualContexts", WrapperNamespace="http://anm.cisco.com", IsWrapped=true)]
    public partial class listVirtualContextsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID deviceIDs;
        
        public listVirtualContextsRequest() {
        }
        
        public listVirtualContextsRequest(ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken, ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID deviceIDs) {
            this.sessionToken = sessionToken;
            this.deviceIDs = deviceIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listVirtualContextsResponse", WrapperNamespace="http://anm.cisco.com", IsWrapped=true)]
    public partial class listVirtualContextsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID[] DeviceIDs;
        
        public listVirtualContextsResponse() {
        }
        
        public listVirtualContextsResponse(ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID[] DeviceIDs) {
            this.DeviceIDs = DeviceIDs;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://anm.cisco.com")]
    public enum SuspendState {
        
        /// <remarks/>
        Graceful,
        
        /// <remarks/>
        Suspend,
        
        /// <remarks/>
        Suspend_Clear_Connections,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://anm.cisco.com")]
    public partial class VMMappingInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DeviceID deviceIDField;
        
        private string sfnameField;
        
        private string sfrsnameField;
        
        private int portField;
        
        private bool portFieldSpecified;
        
        private string ipaddrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DeviceID deviceID {
            get {
                return this.deviceIDField;
            }
            set {
                this.deviceIDField = value;
                this.RaisePropertyChanged("deviceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string sfname {
            get {
                return this.sfnameField;
            }
            set {
                this.sfnameField = value;
                this.RaisePropertyChanged("sfname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string sfrsname {
            get {
                return this.sfrsnameField;
            }
            set {
                this.sfrsnameField = value;
                this.RaisePropertyChanged("sfrsname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
                this.RaisePropertyChanged("port");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool portSpecified {
            get {
                return this.portFieldSpecified;
            }
            set {
                this.portFieldSpecified = value;
                this.RaisePropertyChanged("portSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ipaddr {
            get {
                return this.ipaddrField;
            }
            set {
                this.ipaddrField = value;
                this.RaisePropertyChanged("ipaddr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVMMappingInfo", WrapperNamespace="http://anm.cisco.com", IsWrapped=true)]
    public partial class getVMMappingInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string vmname;
        
        public getVMMappingInfoRequest() {
        }
        
        public getVMMappingInfoRequest(ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken, string vmname) {
            this.sessionToken = sessionToken;
            this.vmname = vmname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVMMappingInfoResponse", WrapperNamespace="http://anm.cisco.com", IsWrapped=true)]
    public partial class getVMMappingInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConDep.Dsl.LoadBalancer.Ace.Ace41.VMMappingInfo[] VMMappingInfos;
        
        public getVMMappingInfoResponse() {
        }
        
        public getVMMappingInfoResponse(ConDep.Dsl.LoadBalancer.Ace.Ace41.VMMappingInfo[] VMMappingInfos) {
            this.VMMappingInfos = VMMappingInfos;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OperationManagerChannel : ConDep.Dsl.LoadBalancer.Ace.Ace41.OperationManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperationManagerClient : System.ServiceModel.ClientBase<ConDep.Dsl.LoadBalancer.Ace.Ace41.OperationManager>, ConDep.Dsl.LoadBalancer.Ace.Ace41.OperationManager {
        
        public OperationManagerClient() {
        }
        
        public OperationManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperationManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperationManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperationManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken login(string user, string password) {
            return base.Channel.login(user, password);
        }
        
        public void logout(ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken) {
            base.Channel.logout(sessionToken);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConDep.Dsl.LoadBalancer.Ace.Ace41.listServerFarmsResponse ConDep.Dsl.LoadBalancer.Ace.Ace41.OperationManager.listServerFarms(ConDep.Dsl.LoadBalancer.Ace.Ace41.listServerFarmsRequest request) {
            return base.Channel.listServerFarms(request);
        }
        
        public ConDep.Dsl.LoadBalancer.Ace.Ace41.Serverfarm[] listServerFarms(ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken, ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID deviceID) {
            ConDep.Dsl.LoadBalancer.Ace.Ace41.listServerFarmsRequest inValue = new ConDep.Dsl.LoadBalancer.Ace.Ace41.listServerFarmsRequest();
            inValue.sessionToken = sessionToken;
            inValue.deviceID = deviceID;
            ConDep.Dsl.LoadBalancer.Ace.Ace41.listServerFarmsResponse retVal = ((ConDep.Dsl.LoadBalancer.Ace.Ace41.OperationManager)(this)).listServerFarms(inValue);
            return retVal.serverfarms;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConDep.Dsl.LoadBalancer.Ace.Ace41.listRserversResponse ConDep.Dsl.LoadBalancer.Ace.Ace41.OperationManager.listRservers(ConDep.Dsl.LoadBalancer.Ace.Ace41.listRserversRequest request) {
            return base.Channel.listRservers(request);
        }
        
        public ConDep.Dsl.LoadBalancer.Ace.Ace41.Rserver[] listRservers(ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken, ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID deviceID) {
            ConDep.Dsl.LoadBalancer.Ace.Ace41.listRserversRequest inValue = new ConDep.Dsl.LoadBalancer.Ace.Ace41.listRserversRequest();
            inValue.sessionToken = sessionToken;
            inValue.deviceID = deviceID;
            ConDep.Dsl.LoadBalancer.Ace.Ace41.listRserversResponse retVal = ((ConDep.Dsl.LoadBalancer.Ace.Ace41.OperationManager)(this)).listRservers(inValue);
            return retVal.Rservers;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConDep.Dsl.LoadBalancer.Ace.Ace41.listServerfarmRserversResponse ConDep.Dsl.LoadBalancer.Ace.Ace41.OperationManager.listServerfarmRservers(ConDep.Dsl.LoadBalancer.Ace.Ace41.listServerfarmRserversRequest request) {
            return base.Channel.listServerfarmRservers(request);
        }
        
        public ConDep.Dsl.LoadBalancer.Ace.Ace41.SfRserver[] listServerfarmRservers(ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken, ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID deviceID, string serverfarmname) {
            ConDep.Dsl.LoadBalancer.Ace.Ace41.listServerfarmRserversRequest inValue = new ConDep.Dsl.LoadBalancer.Ace.Ace41.listServerfarmRserversRequest();
            inValue.sessionToken = sessionToken;
            inValue.deviceID = deviceID;
            inValue.serverfarmname = serverfarmname;
            ConDep.Dsl.LoadBalancer.Ace.Ace41.listServerfarmRserversResponse retVal = ((ConDep.Dsl.LoadBalancer.Ace.Ace41.OperationManager)(this)).listServerfarmRservers(inValue);
            return retVal.SfRservers;
        }
        
        public void addRserverToServerfarm(ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken, ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID deviceID, string serverfarmname, ConDep.Dsl.LoadBalancer.Ace.Ace41.Rserver rserver, int port) {
            base.Channel.addRserverToServerfarm(sessionToken, deviceID, serverfarmname, rserver, port);
        }
        
        public void removeRserverFromServerfarm(ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken, ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID deviceID, ConDep.Dsl.LoadBalancer.Ace.Ace41.SfRserver rserver) {
            base.Channel.removeRserverFromServerfarm(sessionToken, deviceID, rserver);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConDep.Dsl.LoadBalancer.Ace.Ace41.listDeviceIdsResponse ConDep.Dsl.LoadBalancer.Ace.Ace41.OperationManager.listDeviceIds(ConDep.Dsl.LoadBalancer.Ace.Ace41.listDeviceIdsRequest request) {
            return base.Channel.listDeviceIds(request);
        }
        
        public ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID[] listDeviceIds(ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken, ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceType deviceType) {
            ConDep.Dsl.LoadBalancer.Ace.Ace41.listDeviceIdsRequest inValue = new ConDep.Dsl.LoadBalancer.Ace.Ace41.listDeviceIdsRequest();
            inValue.sessionToken = sessionToken;
            inValue.deviceType = deviceType;
            ConDep.Dsl.LoadBalancer.Ace.Ace41.listDeviceIdsResponse retVal = ((ConDep.Dsl.LoadBalancer.Ace.Ace41.OperationManager)(this)).listDeviceIds(inValue);
            return retVal.DeviceIDs;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConDep.Dsl.LoadBalancer.Ace.Ace41.listVirtualContextsResponse ConDep.Dsl.LoadBalancer.Ace.Ace41.OperationManager.listVirtualContexts(ConDep.Dsl.LoadBalancer.Ace.Ace41.listVirtualContextsRequest request) {
            return base.Channel.listVirtualContexts(request);
        }
        
        public ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID[] listVirtualContexts(ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken, ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID deviceIDs) {
            ConDep.Dsl.LoadBalancer.Ace.Ace41.listVirtualContextsRequest inValue = new ConDep.Dsl.LoadBalancer.Ace.Ace41.listVirtualContextsRequest();
            inValue.sessionToken = sessionToken;
            inValue.deviceIDs = deviceIDs;
            ConDep.Dsl.LoadBalancer.Ace.Ace41.listVirtualContextsResponse retVal = ((ConDep.Dsl.LoadBalancer.Ace.Ace41.OperationManager)(this)).listVirtualContexts(inValue);
            return retVal.DeviceIDs;
        }
        
        public void activateServerfarmRserver(ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken, ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID deviceID, ConDep.Dsl.LoadBalancer.Ace.Ace41.SfRserver rserver, string reason) {
            base.Channel.activateServerfarmRserver(sessionToken, deviceID, rserver, reason);
        }
        
        public void suspendServerfarmRserver(ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken, ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID deviceID, ConDep.Dsl.LoadBalancer.Ace.Ace41.SfRserver rserver, ConDep.Dsl.LoadBalancer.Ace.Ace41.SuspendState suspendState, string reason) {
            base.Channel.suspendServerfarmRserver(sessionToken, deviceID, rserver, suspendState, reason);
        }
        
        public void changeServerfarmRserverWeight(ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken, ConDep.Dsl.LoadBalancer.Ace.Ace41.DeviceID deviceID, ConDep.Dsl.LoadBalancer.Ace.Ace41.SfRserver rserver, string reason) {
            base.Channel.changeServerfarmRserverWeight(sessionToken, deviceID, rserver, reason);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConDep.Dsl.LoadBalancer.Ace.Ace41.getVMMappingInfoResponse ConDep.Dsl.LoadBalancer.Ace.Ace41.OperationManager.getVMMappingInfo(ConDep.Dsl.LoadBalancer.Ace.Ace41.getVMMappingInfoRequest request) {
            return base.Channel.getVMMappingInfo(request);
        }
        
        public ConDep.Dsl.LoadBalancer.Ace.Ace41.VMMappingInfo[] getVMMappingInfo(ConDep.Dsl.LoadBalancer.Ace.Ace41.SessionToken sessionToken, string vmname) {
            ConDep.Dsl.LoadBalancer.Ace.Ace41.getVMMappingInfoRequest inValue = new ConDep.Dsl.LoadBalancer.Ace.Ace41.getVMMappingInfoRequest();
            inValue.sessionToken = sessionToken;
            inValue.vmname = vmname;
            ConDep.Dsl.LoadBalancer.Ace.Ace41.getVMMappingInfoResponse retVal = ((ConDep.Dsl.LoadBalancer.Ace.Ace41.OperationManager)(this)).getVMMappingInfo(inValue);
            return retVal.VMMappingInfos;
        }
        
        public bool isEmptyOrNull(string arg0) {
            return base.Channel.isEmptyOrNull(arg0);
        }
        
        public void validateIPAddress(string arg0) {
            base.Channel.validateIPAddress(arg0);
        }
    }
}
