//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConDep.Dsl.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConDep.Dsl.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN CERTIFICATE-----
        ///MIIFdDCCBFygAwIBAgIKJ7dUbQAAAAAAEDANBgkqhkiG9w0BAQUFADBQMRMwEQYK
        ///CZImiZPyLGQBGRYDbmV0MRkwFwYKCZImiZPyLGQBGRYJdG9ycmVzZGFsMR4wHAYD
        ///VQQDExV0b3JyZXNkYWwtSkFULURDMDEtQ0EwHhcNMTIwOTAyMTAxMTU1WhcNMTQw
        ///OTAyMTAxMTU1WjB3MQswCQYDVQQGEwJOTzESMBAGA1UECBMJSG9yZGFsYW5kMQ8w
        ///DQYDVQQHEwZCZXJnZW4xEzARBgNVBAoTCkNvbkRlcC5uZXQxFDASBgNVBAsTC0Rl
        ///dmVsb3BtZW50MRgwFgYDVQQDEw9jb25kZXAudW5pdHRlc3QwgZ8wDQYJKoZIhvcN
        ///AQEBBQADgY0AMIGJAoGBAMlJRaPcNaTr345Whyg/mOcoLtau539bWgteGic9EcZc
        ///Obhz+XfYm7rIfrYfBZm3X [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConDepCert {
            get {
                return ResourceManager.GetString("ConDepCert", resourceCulture);
            }
        }
    }
}
